## Load Dataset

In [22]:
#importing required libraries
import pandas as pd

In [23]:
#Load dataset from GitHub
df = pd.read_csv("https://raw.githubusercontent.com/suryautharakumar/Technology-Dissertation/refs/heads/main/18ProductivityPrediction.csv")

print("Dataset loaded successfully!\n")
print("Shape of dataset:", df.shape)

Dataset loaded successfully!

Shape of dataset: (1197, 15)

## Dataset Understanding

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1197 non-null   object
 1   quarter                1197 non-null   object
 2   department             1197 non-null   object
 3   day                    1197 non-null   object
 4   team                   1197 non-null   int64
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    691 non-null    float64
 8   over_time              1197 non-null   float64
 9   incentive              1197 non-null   float64
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64
 12  no_of_style_change     1197 non-null   int64
 13  no_of_workers          1197 non-null   float64
 14  actual_productivity    1197 non-null   float64
dtypes: float64(8), int64(3), object(4)
memory usage: 140.4+ KB

In [25]:
df.head()

,date,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
0,1/1/2015,Quarter1,sweing,Thursday,8,0.80,26.16,1108.0,7080.0,98.0,0.0,0,0,59.0,0.940725
1,1/1/2015,Quarter1,finishing,Thursday,1,0.75,3.94,NaN,960.0,0.0,0.0,0,0,8.0,0.886500
2,1/1/2015,Quarter1,sweing,Thursday,11,0.80,11.41,968.0,3660.0,50.0,0.0,0,0,30.5,0.800570
3,1/1/2015,Quarter1,sweing,Thursday,12,0.80,11.41,968.0,3660.0,50.0,0.0,0,0,30.5,0.800570
4,1/1/2015,Quarter1,sweing,Thursday,6,0.80,25.90,1170.0,1920.0,50.0,0.0,0,0,56.0,0.800382

In [26]:
#Including categorical columns
df.describe(include='all')

,date,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
count,1197,1197,1197,1197,1197.000000,1197.000000,1197.000000,691.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000
unique,59,5,3,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,1/31/2015,Quarter1,sweing,Wednesday,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,24,360,691,208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,6.426901,0.729632,15.062172,1190.465991,4567.460317,38.210526,0.730159,0.369256,0.150376,34.609858,0.735091
std,NaN,NaN,NaN,NaN,3.463963,0.097891,10.943219,1837.455001,3348.823563,160.182643,12.709757,3.268987,0.427848,22.197687,0.174488
min,NaN,NaN,NaN,NaN,1.000000,0.070000,2.900000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.233705
25%,NaN,NaN,NaN,NaN,3.000000,0.700000,3.940000,774.500000,1440.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.650307
50%,NaN,NaN,NaN,NaN,6.000000,0.750000,15.260000,1039.000000,3960.000000,0.000000,0.000000,0.000000,0.000000,34.000000,0.773333
75%,NaN,NaN,NaN,NaN,9.000000,0.800000,24.260000,1252.500000,6960.000000,50.000000,0.000000,0.000000,0.000000,57.000000,0.850253
max,NaN,NaN,NaN,NaN,12.000000,0.800000,54.560000,23122.000000,25920.000000,3600.000000,300.000000,45.000000,2.000000,89.000000,1.120437

In [27]:
df.isnull().sum()

date                       0
quarter                    0
department                 0
day                        0
team                       0
targeted_productivity      0
smv                        0
wip                      506
over_time                  0
incentive                  0
idle_time                  0
idle_men                   0
no_of_style_change         0
no_of_workers              0
actual_productivity        0
dtype: int64

In [28]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [29]:
categorical_cols = df.select_dtypes(include=['object']).columns

for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

date
date
1/31/2015    24
3/11/2015    24
1/11/2015    23
1/24/2015    23
1/12/2015    23
3/10/2015    23
1/8/2015     22
1/13/2015    22
1/22/2015    22
1/10/2015    22
1/7/2015     22
3/9/2015     22
3/3/2015     22
1/5/2015     22
3/8/2015     22
1/25/2015    21
1/6/2015     21
1/4/2015     21
2/26/2015    21
2/28/2015    21
2/25/2015    21
2/18/2015    21
1/14/2015    21
1/17/2015    21
1/27/2015    21
1/28/2015    21
1/3/2015     21
3/4/2015     21
1/29/2015    20
2/19/2015    20
2/17/2015    20
3/1/2015     20
3/2/2015     20
2/22/2015    20
1/1/2015     19
2/7/2015     19
2/1/2015     19
1/21/2015    19
1/26/2015    19
1/18/2015    19
1/19/2015    19
1/15/2015    19
2/2/2015     19
2/23/2015    19
2/4/2015     19
2/3/2015     19
2/10/2015    19
2/11/2015    19
2/8/2015     19
2/15/2015    19
2/12/2015    19
3/7/2015     19
2/24/2015    19
3/5/2015     19
2/5/2015     18
2/9/2015     18
2/16/2015    18
2/14/2015    17
1/20/2015    15
Name: count, dtype: int64

quarter
quarter
Quarter1    360
Quarter2    335
Quarter4    248
Quarter3    210
Quarter5     44
Name: count, dtype: int64

department
department
sweing        691
finishing     257
finishing     249
Name: count, dtype: int64

day
day
Wednesday    208
Sunday       203
Tuesday      201
Thursday     199
Monday       199
Saturday     187
Name: count, dtype: int64

## Define Target and Features

In [30]:
X = df.drop('actual_productivity', axis=1)
y = df['actual_productivity']

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (1197, 14)
Target shape: (1197,)

## Data Cleaning

In [31]:
X.isnull().sum()

date                       0
quarter                    0
department                 0
day                        0
team                       0
targeted_productivity      0
smv                        0
wip                      506
over_time                  0
incentive                  0
idle_time                  0
idle_men                   0
no_of_style_change         0
no_of_workers              0
dtype: int64

In [32]:
from sklearn.compose import make_column_selector

numeric_features = X.select_dtypes(include=['int64','float64']).columns

categorical_features = X.select_dtypes(include=['object']).columns

print("Numerical Columns")
print(numeric_features)

print("\nCategorical Columns")
print(categorical_features)

Numerical Columns
Index(['team', 'targeted_productivity', 'smv', 'wip', 'over_time', 'incentive',
       'idle_time', 'idle_men', 'no_of_style_change', 'no_of_workers'],
      dtype='object')

Categorical Columns
Index(['date', 'quarter', 'department', 'day'], dtype='object')

In [33]:
from sklearn.impute import SimpleImputer

#Numerical columns
num_imputer = SimpleImputer(strategy='median')
X[numeric_features] = num_imputer.fit_transform(X[numeric_features])

#Categorical columns
cat_imputer = SimpleImputer(strategy='most_frequent')
X[categorical_features] = cat_imputer.fit_transform(X[categorical_features])

print("Missing values after imputation")
print(X.isnull().sum())

Missing values after imputation
date                     0
quarter                  0
department               0
day                      0
team                     0
targeted_productivity    0
smv                      0
wip                      0
over_time                0
incentive                0
idle_time                0
idle_men                 0
no_of_style_change       0
no_of_workers            0
dtype: int64

In [34]:
#One-Hot Encoding
X = pd.get_dummies(X, drop_first=True)

print("Shape after encoding:", X.shape)

Shape after encoding: (1197, 79)

In [35]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(X)

In [36]:
#Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training samples:", X_train.shape)
print("Testing samples:", X_test.shape)

Training samples: (957, 79)
Testing samples: (240, 79)

## Model Building

In [37]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train, y_train)

LinearRegression()

In [38]:
y_pred = lr.predict(X_test)

In [39]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Linear Regression Performance")
print("------------------------------")
print("MAE :", round(mae,4))
print("MSE :", round(mse,4))
print("RMSE:", round(rmse,4))
print("R² Score:", round(r2,4))

Linear Regression Performance
------------------------------
MAE : 0.1121
MSE : 0.0227
RMSE: 0.1506
R² Score: 0.1453

## Compare Multiple Regression Models

In [45]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree Regressor": DecisionTreeRegressor(random_state=42),
    "Random Forest Regressor": RandomForestRegressor(random_state=42),
    "Gradient Boosting Regressor": GradientBoostingRegressor(random_state=42)
}

In [49]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pandas as pd
import numpy as np

results = []

for name, model in models.items():

    # Train model
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Evaluation
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    results.append([name, mae, rmse, r2])

# Create comparison table
results_df = pd.DataFrame(results, columns=[
    "Model",
    "MAE",
    "RMSE",
    "R² Score"
])

results_df.sort_values(by="R² Score", ascending=False).reset_index(drop=True)

                         Model       MAE      RMSE  R² Score
0      Random Forest Regressor  0.070690  0.113198  0.517420
1  Gradient Boosting Regressor  0.078265  0.119858  0.458958
2            Linear Regression  0.112096  0.150645  0.145317
3      Decision Tree Regressor  0.095469  0.164521 -0.019387

In [50]:
best_model = results_df.sort_values(by="R² Score", ascending=False).iloc[0]

print("Best Performing Model")
print("----------------------")
print(best_model)

Best Performing Model
----------------------
Model       Random Forest Regressor
MAE                         0.07069
RMSE                       0.113198
R² Score                    0.51742
Name: 2, dtype: object